export const GET_PLACES = "GET_PLACES";
export const LOADING_PLACES = "LOADING_PLACES";
export const ERROR_PLACES = "ERROR_PLACES";

export const GET_PLACE_TIPS = "GET_PLACE_TIPS";
export const LOADING_PLACE_TIPS = "LOADING_PLACE_TIPS";
export const ERROR_PLACE_TIPS = "ERROR_PLACE_TIPS";

export const GET_PLACE_PHOTOS = "GET_PLACE_PHOTOS";
export const RESET_PLACE_PHOTOS = "RESET_PLACE_PHOTOS";
export const LOADING_PLACE_PHOTOS = "LOADING_PLACE_PHOTOS";
export const ERROR_PLACE_PHOTOS = "ERROR_PLACE_PHOTOS";

export const GET_PLACE_PHOTO = "GET_PLACE_PHOTOS";
export const LOADING_PLACE_PHOTO = "LOADING_PLACE_PHOTOS";
export const ERROR_PLACE_PHOTO = "ERROR_PLACE_PHOTOS";

export const SET_TYPE = "SET_TYPE";

export const GET_LATLONG = "GET_LATLONG";

export const GET_BOUNDS = "GET_BOUNDS";
